name: GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    container:
      image: archlinux:latest
      options: --privileged
    permissions: all
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    steps:
      - uses: actions/checkout@v3
      - name: build
        run: |
            pacman -Syu python python-pip git github-cli --noconfirm
            pip install jdatetime markdown-it-py --break-system-packages
            python generate.py
            
      - name: Deploy to GH Pages 🚀
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: output
